version: "3"
services:
  elasticsearch:
    image: piperra/elasticsearch:7.10.0-arm64
    environment:
      - discovery.type=single-node
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - ELASTIC_PASSWORD=changeme
    ports:
      - "9200:9200"

  kibana:
    depends_on:
      - elasticsearch
    image: piperra/kibana:7.10.0-arm64
    environment:
      - xpack.reporting.enabled=false
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    ports:
      - "5601:5601"
    links:
      - elasticsearch

  filebeat:
    depends_on:
      - kibana
    image: piperra/filebeat:7.10.0-arm64
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    links:
      - kibana
      - elasticsearch
    volumes:
      - ./pcap:/filebeat/pcap

  zeek:
    depends_on:
      - filebeat
    image: piperra/zeek:3.2.2-arm64
    cap_add: ['NET_RAW']
    network_mode: host
    volumes:
      - ./pcap:/pcap
    command:  -i af_packet::wlan0 local

